[package]
name = "sensorhandler"
version = "0.2.3"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
clap = { version = "4.0.4", features = ["derive"] }
evdev = "0.12.0"
